version: '3.0'

expectations:
  population_size: 500000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  data_preparation:
    run: stata-mp:latest analysis/data_preparation_and_descriptives.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data1: output/input_archive_sotro_molnu_20211216_20220210.dta
        data2: output/main_archive_sotro_molnu_20211216_20220210.dta

  cox_regression:
    run: stata-mp:latest analysis/cox.do
    needs: [data_preparation]
    outputs:
      moderately_sensitive:
        log: logs/cox.log
        figure1: output/phtest.svg  
        figure2: output/phtest_psw.svg

  multiple_imputation:
    run: stata-mp:latest analysis/multiple_imputation.do
    needs: [data_preparation]
    outputs:
      moderately_sensitive:
        log: logs/MI.log

