version: '3.0'

expectations:
  population_size: 500000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  data_preparation:
    run: stata-mp:latest analysis/data_preparation_and_descriptives.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data: output/main.dta

  cox_regression:
    run: stata-mp:latest analysis/cox.do
    needs: [data_preparation]
    outputs:
      moderately_sensitive:
        log: logs/cox.log
        figure1: output/phtest.svg  
        figure2: output/phtest_psw.svg

  multiple_imputation:
    run: stata-mp:latest analysis/multiple_imputation.do
    needs: [data_preparation]
    outputs:
      moderately_sensitive:
        log: logs/MI.log

  generate_study_population_update_codelist:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_update_codelist
    outputs:
      highly_sensitive:
        cohort: output/update_codelist/input_update_codelist.csv

  data_preparation_update_codelist:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_update_codelist.do
    needs: [generate_study_population_update_codelist]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_update_codelist.log
      highly_sensitive:
        data: output/update_codelist/main_update_codelist.dta

  cox_regression_update_codelist:
    run: stata-mp:latest analysis/cox_update_codelist.do
    needs: [data_preparation_update_codelist]
    outputs:
      moderately_sensitive:
        log: logs/cox_update_codelist.log
        figure1: output/update_codelist/phtest.svg  
        figure2: output/update_codelist/phtest_psw.svg


  generate_study_population_BA2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_BA2
    outputs:
      highly_sensitive:
        cohort: output/BA2/input_BA2.csv

  data_preparation_BA2:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_BA2.do
    needs: [generate_study_population_BA2]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_BA2.log
      highly_sensitive:
        data: output/BA2/main_BA2.dta

  cox_regression_BA2:
    run: stata-mp:latest analysis/cox_BA2.do
    needs: [data_preparation_BA2]
    outputs:
      moderately_sensitive:
        log: logs/cox_BA2.log
        figure1: output/BA2/phtest.svg  
        figure2: output/BA2/phtest_psw.svg


  generate_study_population_ukrr:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ukrr
    outputs:
      highly_sensitive:
        cohort: output/ukrr/input_ukrr.csv
        
  data_preparation_ukrr:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_ukrr.do
    needs: [generate_study_population_ukrr]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_ukrr.log
      highly_sensitive:
        data: output/ukrr/main_ukrr.dta

  cox_regression_ukrr:
    run: stata-mp:latest analysis/cox_ukrr.do
    needs: [data_preparation_ukrr]
    outputs:
      moderately_sensitive:
        log: logs/cox_ukrr.log
        figure1: output/ukrr/phtest.svg  
        figure2: output/ukrr/phtest_psw.svg
        figure3: output/ukrr/psgraph.svg

  multiple_imputation_ukrr:
    run: stata-mp:latest analysis/multiple_imputation_ukrr.do
    needs: [data_preparation_ukrr]
    outputs:
      moderately_sensitive:
        log: logs/MI_ukrr.log

  generate_study_population_ukrr_untreated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ukrr_untreated
    outputs:
      highly_sensitive:
        cohort: output/ukrr/input_ukrr_untreated.csv

  data_preparation_ukrr_untreated:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_ukrr_untreated.do
    needs: [generate_study_population_ukrr_untreated, data_preparation_ukrr]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_ukrr_untreated.log
      highly_sensitive:
        data1: output/ukrr/ukrr_untreated.dta
        data2: output/ukrr/main_ukrr_untreated.dta

  cox_regression_ukrr_untreated:
    run: stata-mp:latest analysis/cox_ukrr_untreated.do
    needs: [data_preparation_ukrr_untreated]
    outputs:
      moderately_sensitive:
        log: logs/cox_ukrr_untreated.log


  data_preparation_ukrr_raw_rate:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_ukrr_raw_rate.do
    needs: [generate_study_population_ukrr]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_ukrr_raw_rate.log

  generate_study_population_ukrr_update:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ukrr_update
    outputs:
      highly_sensitive:
        cohort: output/ukrr/input_ukrr_update.csv
        
  data_preparation_ukrr_update:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_ukrr_update.do
    needs: [generate_study_population_ukrr_update]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_ukrr_update.log
      highly_sensitive:
        data: output/ukrr/main_ukrr_update.dta

  cox_regression_ukrr_update:
    run: stata-mp:latest analysis/cox_ukrr_update.do
    needs: [data_preparation_ukrr_update]
    outputs:
      moderately_sensitive:
        log: logs/cox_ukrr_update.log
        figure1: output/ukrr/phtest_update.svg  
        figure2: output/ukrr/phtest_psw_update.svg
        figure3: output/ukrr/psgraph_update.svg

  generate_study_population_anaphylaxis:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_anaphylaxis
    outputs:
      highly_sensitive:
        cohort: output/input_anaphylaxis.csv

  anaphylaxis:
    run: stata-mp:latest analysis/anaphylaxis.do
    needs: [generate_study_population_anaphylaxis]
    outputs:
      moderately_sensitive:
        log: logs/anaphylaxis.log

  generate_study_population_anaphylaxis_untreated:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_anaphylaxis_untreated
    outputs:
      highly_sensitive:
        cohort: output/input_anaphylaxis_untreated.csv

  anaphylaxis_untreated:
    run: stata-mp:latest analysis/anaphylaxis_untreated.do
    needs: [generate_study_population_anaphylaxis_untreated]
    outputs:
      moderately_sensitive:
        log: logs/anaphylaxis_untreated.log

  generate_study_population_anaphylaxis_update:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_anaphylaxis_update
    outputs:
      highly_sensitive:
        cohort: output/input_anaphylaxis_update.csv

  anaphylaxis_update:
    run: stata-mp:latest analysis/anaphylaxis_update.do
    needs: [generate_study_population_anaphylaxis_update]
    outputs:
      moderately_sensitive:
        log: logs/anaphylaxis_update.log

  anaphylaxis_update_R:
    run: r:latest  analysis/anaphylaxis_update.R
    needs: [generate_study_population_anaphylaxis_update]
    outputs:
      moderately_sensitive:
        log: logs/anaphylaxis_update.txt


  generate_study_population_anaphylaxis_untreated_update:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_anaphylaxis_untreated_update
    outputs:
      highly_sensitive:
        cohort: output/input_anaphylaxis_untreated_update.csv

  anaphylaxis_untreated_update:
    run: stata-mp:latest analysis/anaphylaxis_untreated_update.do
    needs: [generate_study_population_anaphylaxis_untreated_update]
    outputs:
      moderately_sensitive:
        log: logs/anaphylaxis_untreated_update.log

  anaphylaxis_untreated_update_R:
    run: r:latest analysis/anaphylaxis_untreated_update.r
    needs: [generate_study_population_anaphylaxis_untreated_update]
    outputs:
      moderately_sensitive:
        log: logs/anaphylaxis_untreated_update.txt

  generate_study_population_feasibility:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_feasibility
    outputs:
      highly_sensitive:
        cohort: output/input_feasibility.csv

  data_preparation_feasibility:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_feasibility.do
    needs: [generate_study_population_feasibility]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_feasibility.log
      highly_sensitive:
        data: output/main_feasibility.dta

  generate_study_population_feasibility2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_feasibility2
    outputs:
      highly_sensitive:
        cohort: output/input_feasibility2.csv

  # Study population for NICE figures 26th February 2024
  generate_study_population_nice:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_nice
    outputs:
      highly_sensitive:
        cohort: output/input_nice.csv

  nice_data:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_nice.do
    needs: [generate_study_population_nice]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_nice.log
        table: output/nice/mortality_nice.txt