version: '3.0'

expectations:
  population_size: 500000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv



  multiple_imputation:
    run: stata-mp:latest analysis/multiple_imputation.do
    needs: [data_preparation]
    outputs:
      moderately_sensitive:
        log: logs/MI.log

  generate_study_population_update_codelist:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_update_codelist
    outputs:
      highly_sensitive:
        cohort: output/update_codelist/input_update_codelist.csv

  data_preparation_update_codelist:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_update_codelist.do
    needs: [generate_study_population_update_codelist]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_update_codelist.log
      highly_sensitive:
        data: output/update_codelist/main_update_codelist.dta

  cox_regression_update_codelist:
    run: stata-mp:latest analysis/cox_update_codelist.do
    needs: [data_preparation_update_codelist]
    outputs:
      moderately_sensitive:
        log: logs/cox_update_codelist.log
        figure1: output/update_codelist/phtest.svg  
        figure2: output/update_codelist/phtest_psw.svg


  generate_study_population_Paxlovid:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_Paxlovid
    outputs:
      highly_sensitive:
        cohort: output/Paxlovid/input_Paxlovid.csv

  data_preparation_Paxlovid:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_Paxlovid.do
    needs: [generate_study_population_Paxlovid]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_Paxlovid.log
      highly_sensitive:
        data: output/Paxlovid/main_Paxlovid.dta

  generate_study_population_BA2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_BA2
    outputs:
      highly_sensitive:
        cohort: output/BA2/input_BA2.csv



  generate_study_population_ukrr:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ukrr
    outputs:
      highly_sensitive:
        cohort: output/ukrr/input_ukrr.csv
        
  data_preparation_ukrr:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_ukrr.do
    needs: [generate_study_population_ukrr]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_ukrr.log
      highly_sensitive:
        data: output/ukrr/main_ukrr.dta

  data_preparation:
    run: stata-mp:latest analysis/data_preparation_and_descriptives.do
    needs: [generate_study_population_ukrr]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data: output/main.dta

  cox_regression:
    run: stata-mp:latest analysis/cox.do
    needs: [data_preparation]
    outputs:
      moderately_sensitive:
        log: logs/cox.log
        figure1: output/phtest.svg  
        figure2: output/phtest_psw.svg

  data_preparation_BA2:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_BA2.do
    needs: [generate_study_population_ukrr]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_BA2.log
      highly_sensitive:
        data: output/BA2/main_BA2.dta

  cox_regression_BA2:
    run: stata-mp:latest analysis/cox_BA2.do
    needs: [data_preparation_BA2]
    outputs:
      moderately_sensitive:
        log: logs/cox_BA2.log
        figure1: output/BA2/phtest.svg  
        figure2: output/BA2/phtest_psw.svg
