version: '3.0'

expectations:
  population_size: 100000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  data_preparation:
    run: stata-mp:latest analysis/data_preparation_and_descriptives.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data: output/main.dta